default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: thundrs_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: thundrs_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: thundrs_production
  pool: 5
